### PR TITLE
testing pydantic v1.10.0a2

### PR DESCRIPTION
**Pull request by samuelcolvin**
### TO NOT MERGE

This is pull request is just to test pydantic v1.10, see https://github.com/pydantic/pydantic/discussions/4359

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Hi, please can you kick off tests so I can check if v1.10 will break anything.

**Comment by yezz123** [comment]
> Hi, please can you kick off tests so I can check if v1.10 will break anything.

Hi @samuelcolvin, yes for sure 🚀

**Comment by yezz123** [comment]
It's Done! 🥳 I guess the pre-release work fine with pydantic v1.10 🕺🏻

**Comment by samuelcolvin** [comment]
thanks great news, thanks.

**Pull request closed without merging**
