### PR TITLE
✨ Pydantic v2 migration

### PR DESCRIPTION
**Pull request by yezz123**

### CODE REVIEW

**Comment by patrick91** [comment]
@yezz123 is there anything I can do to help you land this PR?

**Comment by yezz123** [comment]
Hey, @patrick91, thanks for reaching out and your willingness to help 🙏🏻 

I really appreciate it. I've been taking some time off recently, but I'm now back and ready to start reviewing the changes in this PR and push some updates.

My main idea of supporting both versions of Pydantic sounds excellent and will definitely help maintain broader compatibility.

Please let me know if you have any specific suggestions or areas you'd like to contribute to.

Thanks again for your support 🙌🏻

**Comment by artemonsh** [comment]
any updates?

**Comment by yezz123** [comment]
> Any updates?

I'm thinking of keeping this one until I finish the documentation and then I will get back to it, it's on my milestone 🙏🏻

**Pull request closed without merging**
